### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by guerreiropedr0** [guerreiropedr0/recipe-app#30]
In this issue, we:
- Added an automated kanban board
- Created issues that redirected to the kanban board
- Assigned the tasks equally to three different students:
- - @gtekle - Student A
- - @oluyaratosin123 - Student C
- - @guerreiropedr0 - Student B

[Here](https://github.com/guerreiropedr0/recipe-app/projects/1) is the link for the project.

**Comment by dasileker** [comment]
### **Hi @guerreiropedr0,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
